sudo: false
language: python
env:
- DJANGO_SETTINGS_MODULE=representatives.tests.settings
python:
- "2.7"
before_install:
- pip install codecov
install:
- pip install -e .[api,testing]
script:
- pep8 representatives/ --exclude migrations --ignore E128
- flake8 representatives/ --exclude migrations --ignore E128
- django-admin migrate
- cat representatives/contrib/francedata/tests/representatives_input.json | francedata_import_representatives
- cat representatives/contrib/parltrack/tests/representatives_fixture.json | parltrack_import_representatives
- py.test
after_success:
- codecov
