sudo: false
env:
  global:
  - DJANGO_DEBUG=True
  - DJANGO_SETTINGS_MODULE=memopol.settings
language: python
python:
- '2.7'
services:
- postgresql
install:
- pip install -U setuptools
- pip install git+https://github.com/njoyard/django-responsediff.git@fix-selectors-encoding
- pip install -e .[testing]
before_script:
- bin/install_client_deps.sh
- psql -c "CREATE USER memopol WITH CREATEDB PASSWORD 'memopol';" -U postgres
- psql -c "CREATE DATABASE memopol WITH OWNER memopol;" -U postgres
script:
- flake8 . --exclude '*/migrations,docs,static' --ignore E128
- py.test memopol representatives_positions representatives_recommendations
- django-admin migrate
after_success:
- codecov
deploy:
- provider: openshift
  edge: true
  user: memopol@laquadrature.net
  password:
    secure: atDq1NEkHXOsV2gZKeXAIn+PvbL3jduz3WK1qIs7BSHyNbrZMT1OUmvoXXrM8+i5eqW3TNsvp23w0RuD06wxSjHkPl+ZCEXP1Ao98p85UZNCgixxiwZHEhL6Amz5vqueGhv+47VOIKNgNFb9NAtRrWyIdA9xDUiK2oWkMSDmHas=
  app: master
  domain: memopol
  deployment_branch: master
  on:
    repo: political-memory/political_memory
    branch: master
