sudo: false
env:
  - DJANGO_DEBUG=True DJANGO_SETTINGS_MODULE=memopol.settings
language: python
python:
- '2.7'
install:
- pip install -e .
- pip install flake8 pep8
before_script:
- bin/install_client_deps
script:
- pep8 . --exclude '*/migrations,docs,static' --ignore E128
- flake8 . --exclude '*/migrations,docs,static' --ignore E128
- django-admin migrate
- django-admin update_score
deploy:
- provider: openshift
  user: jamespic@gmail.com
  password:
    secure: W7hQDKAtmpOfwLjBuss6NEKqPSrRhsbgH8a8eV+/Oo6HZxMi1mbNFSi+6WRNSs3Cil0ZZV+awoqC61jIzV4oTwEYcy5bv9NWNSY1QO34DECMS5sY00wA0zKhkdsdTr9Pc3TLRp1cw6x2KNCF356FKZojFTRbjtfJ79rqBc5k5ww=
  app: dev
  domain: memopol
  skip_cleanup: true
  deployment_branch: pr
  on:
    repo: political-memory/political_memory
    branch: pr
