from setuptools import setup

setup(name='political-memory',
    version='0.0.1',
    description='OpenShift App',
    packages=['political_memory'],
    package_dir={'political_memory': '.'},
    author='Laurent Peuch',
    author_email='cortex@worlddomination.be',
    url='http://github.com/political-memory/political_memory/',
    install_requires=[
        'django>1.8,<1.9',
        'hamlpy',
        'django-bootstrap3',
        'django-constance[database]',
        'django-compressor',
        'django-coffeescript',
        'python-dateutil',
        'django-autocomplete-light',
        'django-datetime-widget',
        'django-filter',
        'django-taggit',
        'django-representatives',
        'django-representatives-votes',
        'ijson',
        'pytz',
    ],
)
