#!/bin/bash
set -x

cmd=$1

if [ -z "$cmd" ]; then
    ${OPENSHIFT_REPO_DIR}.openshift/cron/daily/update_database representatives
    ${OPENSHIFT_REPO_DIR}.openshift/cron/daily/update_database dossiers
    ${OPENSHIFT_REPO_DIR}.openshift/cron/daily/update_database votes
    exit 0
fi

[ $cmd = representatives ] && file=ep_meps_current.json.xz
[ $cmd = dossiers ] && file=ep_dossiers.json.xz
[ $cmd = votes ] && file=ep_votes.json.xz

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate

pushd ${OPENSHIFT_DATA_DIR}
    rm -rf $file  # ensure daily
    wget http://parltrack.euwiki.org/dumps/$file || exit 1

    cd ${OPENSHIFT_REPO_DIR}
    export DJANGO_SETTINGS_MODULE=memopol.settings
    unxz -c ${OPENSHIFT_DATA_DIR}$file | parltrack_import_$cmd

    [ $cmd = representatives ] && ./manage.py update_score
    rm -rf $file
popd
